var age = 25;
age = true;
console.log(age);
age = "twenty-five";
console.log(age);
age = { name: "luigi" };
console.log(age);
var mixed = [];
mixed.push("mario");
mixed.push(5);
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: "yoshi", age: 25 };
console.log(ninja);
